# Generated by Django 4.2.20 on 2025-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('qty', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.DecimalField(decimal_places=5, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('net', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('notes', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
